In [1]:
using PlutoUI

In [2]:
Print("Hello World")

Hello World

## Core Language Basics
In this notebook, we explore the core language features of Julia. There is a nice talk from the JuliaCon 2020 about Pluto notebooks, which is freely available on YouTube (https://www.youtube.com/watch?v=IAF8DjrQSSk). Most of the things mentioned there (if not all), works here as well.

Notice that Julia notebooks do not support multi-line cells. This is by design. If we want to use them anyway, we must wrap them into the following code.

```julia
begin

end
```

**UPDATE:** Strangely, it started to work without the above block!

### Variables
Julia is fully unicode and this applies even to variable names. What makes this incredibly amazing is that we can type mathematical formulas directly into code, thus let us imagine that we want to calculate the chromatic number of a graph, then instead of naming our variable 'chi' we can actually use the greek letter by typing '\chi', which is incredible.

### Type System
Julia is inbetween statically typed (like Java) and dynamically typed (like Python and JavaScript) languages. In the Julia programming language all variable bindings have a specific type which can be provided by the developer. However, if no specific type is provided, then this type is the abstract supertype named 'Any'.

We can annotate any variable using the `::` operator which reads as 'is an instance of'.

Notice that variable scopes are global in Julia by design. However, we can introduce local variables by using local scopes. An in-depth documentation of this feature is provided in the official [documentation](https://docs.julialang.org/en/v1/manual/variables-and-scoping/).

In [4]:
# Assigning a variable
a = 45

45

In [5]:
a

45

In [6]:
begin
    α=42
    χ=2*α+25
end

109

In [7]:
# This is a comment. Full unicode support allows crazy things such as.
😀 = "😀"

"😀"

In [8]:
if 😀 == 😀
    Print("Hello")
end

Hello

In [9]:
# check type
typeof("Hello")

String

In [10]:
# annotated typed local variable by using the let end block.
begin
    let 
        a::Int=42 
        print(a)
    end
end

42

In [11]:
# default integer type
typeof(42)

Int64

In [12]:
# default floating point type
typeof(42.42)

Float64

In [13]:
# we can define a formal symbol by using the : operator
:x

:x

In [14]:
typeof(:x)

Symbol

In [15]:
# separating different arguments for println are not done by default
println(42, 42)

4242


In [16]:
# type conversion. if we have a list of different types, e.g. integers and floats mixed, then julia will convert everything to floating. This concept improves performance!
println([ 4+42, 3*4, 3/4])

[46.0, 12.0, 0.75]


In [17]:
typeof([4.0, 1, 2, 42])

Vector{Float64} (alias for Array{Float64, 1})

In [18]:
# We have builtin support for rational numbers!!! (using double //)
typeof(5//2)

Rational{Int64}

In [19]:
# using standard boolean operators as in python. notice that println does not seem to work here, we use PlutoUI Print function.
begin
    a = true
    b = false
    if a && b
        Print("hello world")
    elseif a || b
        Print("hello world 2")
    elseif !a
        Print("hello world 3")
    end
end

hello world 2

In [20]:
# we can join strings as follows
join([42, 42], " ")

"42 42"

In [21]:
# we can repeat any variable as follows
"abc"^3

"abcabcabc"

In [22]:
# Basic control structure
n = 42
if n > 1 && n < 23
    println("Hello World")
elseif n % 3 == 0
    println("Divisible by 3")
else
    println(n)
end

Divisible by 3


In [23]:
# Inline ternary operator
x = n > 42 ? 0 : n

42

In [24]:
# while loop. notice that there is no "i++" statement but we can use the shorthand notation "i += 1"
i = 0
while i < 42
    print(i)
    i += 1
end

01234567891011121314151617181920212223242526272829303132333435363738394041

In [4]:
# for loop
arr = [1, 2, 3, 4, 5, 6, 7, 8]
for x in arr
    print(x)
end

12345678

In [26]:
# we have a "range" like construct as we have in Python
for var in 1:20
    print(var)
end

1234567891011121314151617181920

In [27]:
# there is no native "do while loop" in julia. However, there is this really cool construct.
while true
    3 > 2 && break
end
println("we are finished")

we are finished


In [29]:
# create a collection
collection = [42, 41, 40, 39, 2]

5-element Vector{Int64}:
 42
 41
 40
 39
  2

In [30]:
typeof(collection)

Vector{Int64} (alias for Array{Int64, 1})

In [35]:
# if we have a collection with one float, then the whole list is converted to float for performance reasons
collection2 = [42, 42.0]
typeof(collection2)

Vector{Float64} (alias for Array{Float64, 1})

In [ ]:
# it is interesting that this does not happen if we append a floating point number and mutate the passed collection using the ! operator
append!(collection, 2.0)

In [36]:
typeof(collection)

Vector{Int64} (alias for Array{Int64, 1})

In [38]:
# having a mixed collection, then this collection is going to be of type any. This is the type on top of Julias type hierarchy. This has obvious performance slowdowns.
collection3 = [1, 2, 3 ,4, "2"]

5-element Vector{Any}:
 1
 2
 3
 4
  "2"

In [39]:
typeof(collection3)

Vector{Any} (alias for Array{Any, 1})

In [43]:
# ATTENTION julia used 1 index based arrays. this is different from almost all other languages
arr = [1, 2, 3, 4, 5]
println(arr[1])

1


In [44]:
# create a copy of "collection"
copyCollection = collection[:]

6-element Vector{Int64}:
 42
 41
 40
 39
  2
  2

In [45]:
# or from the 2nd element to the end
copyCollection2 = collection[2:end]

5-element Vector{Int64}:
 41
 40
 39
  2
  2

Comming from python, we are tempted to use collection[:4], however since :4 is just a formal symbol, this won't work here, we need to call collection[1:end] here

In [50]:
# access the last element
collection[end]

2

In [51]:
# mutate collections
arr = [1, 2, 3, 4, 5]
arr[1] = 2
println(arr)

[2, 2, 3, 4, 5]


In [52]:
# the following is useful for debugging
@show arr;

arr = [2, 2, 3, 4, 5]


In [53]:
# create a copy
collectionCopy = copy(arr)

5-element Vector{Int64}:
 2
 2
 3
 4
 5

In [54]:
# tuples. they are similar to arrays but are immutable
tuple = (1, 2, 3)

(1, 2, 3)

In [56]:
# we can name them inline as follows
namedTuple = (firstName="David", lastName="Scholz")
println(namedTuple.firstName)

David


In [57]:
# create dictonaries
d = Dict("FirstName" => "David", "LastName" => "Scholz")
println(d["FirstName"])

David


In [58]:
# add a new value
d["hobby"] = "Julia Language"
println(d)

Dict("hobby" => "Julia Language", "LastName" => "Scholz", "FirstName" => "David")


In [59]:
poppedValue = pop!(d)

"hobby" => "Julia Language"

In [60]:
println(d)

Dict("LastName" => "Scholz", "FirstName" => "David")


In [66]:
d2 = Dict("Hobby" => "Julia Language")
# merge d with d2
merge!(d, d2)
println(d)
println(d2)

Dict("LastName" => "Scholz", "FirstName" => "David", "Hobby" => "Julia Language")
Dict("Hobby" => "Julia Language")


In [69]:
# iterate over keys and values at the same time. notice the notation via $.
for (k, v) in d
    println("key=$k \t value=$v")
end

key=LastName 	 value=Scholz
key=FirstName 	 value=David
key=Hobby 	 value=Julia Language


In [70]:
# In Julia, it is even possible to use symbols as keys!
symbolDict = Dict(:hobby => "Julia Language")
@show symbolDict

symbolDict = Dict(:hobby => "Julia Language")


Dict{Symbol, String} with 1 entry:
  :hobby => "Julia Language"

Julia provides an excellent support for arrays, matrices and tensors

In [78]:
# 1 dimensional array
vector = [1, 2, 3]
typeof(vector)
@show vector
# push element to the end
push!(vector, 1)
@show vector
# pop the last element
pop!(vector)
@show vector

vector = [1 2 3]
vector = [1, 2, 3]
vector = [1, 2, 3, 1]
vector = [1, 2, 3]


3-element Vector{Int64}:
 1
 2
 3

In [79]:
# a two dimensional array is constructed as usual. we use a list of lists
arr = [
    [1, 2 ,3],
    [1, 2, 3],
    [1, 2, 3]
]
typeof(arr)

Vector{Vector{Int64}} (alias for Array{Array{Int64, 1}, 1})

In [76]:
# However, in Julia we can create actual matrices as well!
vector = [1 2 3]
typeof(vector)
# we can transpose as follows
y = vector'
typeof(y)
typeof(vector)
@show y

y = [1; 2; 3;;]


3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 2
 3

In [80]:
# this of course works for 2 dimensional matrices as well
matrix = [
    [1 2 3]
    [4 5 6]
    [7 8 9]
]
@show matrix

matrix = [1 2 3; 4 5 6; 7 8 9]


3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [81]:
size(matrix) #3x3 matrix

(3, 3)

In [83]:
# matrices can be reshaped as follows (this works column wise)
matrix2 = reshape(matrix, 9,1)

9×1 Matrix{Int64}:
 1
 4
 7
 2
 5
 8
 3
 6
 9

In [84]:
# we can create some random matrices (4x3 matrix of random values between 0 and 1)
randMatrix = rand(4, 3)

4×3 Matrix{Float64}:
 0.7414      0.0916452  0.879098
 0.522885    0.981919   0.403239
 0.799681    0.950792   0.469104
 0.00590864  0.996708   0.967143

In [85]:
# these python constructions also work in Julia
a = [i^2 for i in 1:20]
println(a)
# create an array of tuples using two for loops. this can be done in a single line
b = [(i, j^2) for i in 1:5, j in 6:10]
println(b)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]
[(1, 36) (1, 49) (1, 64) (1, 81) (1, 100); (2, 36) (2, 49) (2, 64) (2, 81) (2, 100); (3, 36) (3, 49) (3, 64) (3, 81) (3, 100); (4, 36) (4, 49) (4, 64) (4, 81) (4, 100); (5, 36) (5, 49) (5, 64) (5, 81) (5, 100)]


In [86]:
# we can fill up an array as follows
A = fill(0, (3, 3))

3×3 Matrix{Int64}:
 0  0  0
 0  0  0
 0  0  0

In [97]:
# julia has a nice linear algebra package
using LinearAlgebra
A = fill(5, (3, 3))
det(A)
# transpose
A'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 5  5  5
 5  5  5
 5  5  5

In [110]:
# we can solve linear equations as follows
A = rand(3, 3)
x = fill(3, (3, ))
b = A*x
println(b)
# solve for x
A\b

[2.0590644044832302, 4.186954778917233, 3.7691967771097037]


3-element Vector{Float64}:
 2.9999999999999645
 2.999999999999841
 3.0000000000003957

In [116]:
# we can have tensors (n dimensional array) as well, e.g. 4x3x2
tensor = rand(4, 3 ,2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.448972  0.445571  0.563995
 0.645816  0.921272  0.18862
 0.346873  0.600855  0.734782
 0.592508  0.989557  0.927294

[:, :, 2] =
 0.115914  0.94012   0.385235
 0.601929  0.215477  0.685085
 0.293325  0.591033  0.408072
 0.990873  0.354649  0.332656

In [117]:
# we have complex numbers in Julia builtin as well. The 'im' is a builtin in Julia for the imaginary part
c = 1 + 3*im
@show c

c = 1 + 3im


1 + 3im

In [121]:
# we can check data types in Julia as follows
isa(c, Complex)

true

In [125]:
# in Julia we do not need a explicit return statement. The last statement will be returned
function square(x)
    x * x
end
println(square(2))
# we can include the return anyway if we want to improve readability
function square2(x)
    return x*x
end
println(square2(2))

4
4


In [127]:
# we can create shorthand one line functions as follows
divide(x, y) = x / y
divide(4, 2)

2.0

In [129]:
# by convention, we append a ! infront of functions that mutate data, e.g.
function replace!(arr, index, value)
    arr[index] = value
end
array = [1, 2, 3]
replace!(array, 1, 4)
println(array)

[4, 2, 3]


In [133]:
# overloading functions is also possible
function number(x::Int64)
    x
end

function number(x::Float64)
    x
end

println(number(4))
println(number(4.0))

4
4.0


In [134]:
methods(number)

# 2 methods for generic function "number":
[1] number(x::Int64) in Main at /home/pgrepds/Documents/Lager/julia-playground/core.ipynb:2
[2] number(x::Float64) in Main at /home/pgrepds/Documents/Lager/julia-playground/core.ipynb:6

In [136]:
# notice that this speeds up logic, since we could implement certain methods for all the different data types (have a look at methods(+) for an example)

In [137]:
# we can create lambdas, anonyomous functions as well
a = x -> x^2
a(2)

4

In [139]:
# we can the usual stuff with this, e.g. filtering arrays on the fly
arr = [1, 2, 3, 4, 5, 6, 7]
filter!(x -> x % 2 == 0, arr)

3-element Vector{Int64}:
 2
 4
 6

In [140]:
# We can define a symbol to be a function. we can do crazy stuff with this, e.g.
≠ = !=
println(3 ≠ 4)

true


In [141]:
# we can use something that is called splatting
f = (a, b, c) -> println("$a $b $c")
arr = [1, 2, 3]
f(arr...) # since f takes three arguments, we can "split" the array arr using the three dot operator

1 2 3


In [142]:
# using reduce
collection = [1, 2, 3, 4, 5]
reduce(+, collection)

15

In [143]:
# apply a function to each element of a collection
collection = [1, 2, 3, 4, 5]
broadcast(x -> x*2, collection)

5-element Vector{Int64}:
  2
  4
  6
  8
 10

In [145]:
# julia has a dedicated operator for this called the dot operator
(x-> x*4).(collection)

5-element Vector{Int64}:
  4
  8
 12
 16
 20

In [146]:
# the builtin functions can be used in a similar way, e.g.
a = collection .+ 1

5-element Vector{Int64}:
 2
 3
 4
 5
 6

In [147]:
# or using multiplication
collection .* 2

5-element Vector{Int64}:
  2
  4
  6
  8
 10

In [148]:
# we can even write something like the following to do the same thing
2collection

5-element Vector{Int64}:
  2
  4
  6
  8
 10