In [19]:
using Measurements

In [33]:
A = zeros(Measurement{Float64},5,1) # we need to provide a type here
for n = 1:5
  local B = rand() ± rand()
  local C = rand() ± rand()
  global A[n,1] = sqrt.((B-C).^2)
end
A

5×1 Matrix{Measurement{Float64}}:
  0.64 ± 0.55
  0.33 ± 0.21
  0.53 ± 0.78
 0.078 ± 0.64
  0.42 ± 0.61

In [35]:
v = collect(range(1e10, -1e10, step=-1e8))
deleteat!(v,findall(iszero,v))

200-element Vector{Float64}:
  1.0e10
  9.9e9
  9.8e9
  9.7e9
  9.6e9
  9.5e9
  9.4e9
  9.3e9
  9.2e9
  9.1e9
  ⋮
 -9.2e9
 -9.3e9
 -9.4e9
 -9.5e9
 -9.6e9
 -9.7e9
 -9.8e9
 -9.9e9
 -1.0e10

In [36]:
faces = ["bold", "ital", "code"]
str = "The font face is "

map(x -> str*x, faces)

3-element Vector{String}:
 "The font face is bold"
 "The font face is ital"
 "The font face is code"

In [39]:
faces = ["bold", "ital", "code"]
str = "The font face is "
["The font face is $f" for f ∈ faces]

3-element Vector{String}:
 "The font face is bold"
 "The font face is ital"
 "The font face is code"